version: "3.8"

services:
  nodejs:
    container_name: nodejs
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - node-prometheus-grafana

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - nodejs
    networks:
      - node-prometheus-grafana
    restart: always

volumes:
  prometheus-data:

networks:
  node-prometheus-grafana:
